# Previous Config

## Packages and folders

In [ ]:
!pip install -U ranx sentence-transformers datasets accelerate #xformers
!pip uninstall -y wandb

import argparse
import itertools
import json
import os
import re
import time
import tempfile
import unicodedata
import shutil
import logging
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from ranx import Qrels, Run, evaluate
from sentence_transformers import SentenceTransformer, losses, SentenceTransformerTrainer, SentenceTransformerTrainingArguments, InputExample, losses, util, evaluation
from sentence_transformers.training_args import BatchSamplers
from datasets import Dataset
from transformers import EarlyStoppingCallback
from huggingface_hub import list_models, model_info, snapshot_download, login, whoami
from google.colab import userdata

import psutil
import multiprocessing as mp
import traceback
import gc
from multiprocessing import Process, Queue
import signal
import sys

Collecting ranx
  Downloading ranx-0.3.21-py3-none-any.whl.metadata (17 kB)
Collecting sentence-transformers
  Downloading sentence_transformers-5.1.2-py3-none-any.whl.metadata (16 kB)
Collecting datasets
  Downloading datasets-4.4.1-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.12.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from ranx) (2.0.2)
Requirement already satisfied: numba>=0.54.1 in /usr/local/lib/python3.12/dist-packages (from ranx) (0.62.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from ranx) (2.2.2)
Collecting tabulate (from ranx)
  Downloading tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from ranx) (4.67.1)
Requirement already satisfied: scipy>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from ranx) (1.16.3)
Collecting ir-datasets (from ranx)
  Downloading ir_datasets-0.5.11-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from ranx) (14.2.0)
Collecting orjson (from ranx)
  Downloading orjson-3.11.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.6/41.6 kB 3.1 MB/s eta 0:00:00
Collecting lz4 (from ranx)
  Downloading lz4-4.4.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Collecting cbor2 (from ranx)
  Downloading cbor2-5.7.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.4 kB)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (from ranx) (0.13.2)
Collecting fastparquet (from ranx)
  Downloading fastparquet-2024.11.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.57.3)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.9.0+cpu)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (0.36.0)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (12.0.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.20.0)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (22.0.0)
Collecting dill<0.4.1,>=0.3.0 (from datasets)
  Downloading dill-0.4.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.6.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting multiprocess<0.70.19 (from datasets)
  Downloading multiprocess-0.70.18-py312-none-any.whl.metadata (7.5 kB)
Collecting fsspec<=2025.10.0,>=2023.1.0 (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets)
  Downloading fsspec-2025.10.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate) (0.7.0)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets)
  Downloading aiohttp-3.13.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.1 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.12.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2025.11.12)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.2.0)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.54.1->ranx) (0.45.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.22.1)
Collecting cramjam>=2.3 (from fastparquet->ranx)
  Downloading cramjam-2.11.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->ranx) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->ranx) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->ranx) (2025.2)
Requirement already satisfied: beautifulsoup4>=4.4.1 in /usr/local/lib/python3.12/dist-packages (from ir-datasets->ranx) (4.13.5)
Collecting inscriptis>=2.2.0 (from ir-datasets->ranx)
  Downloading inscriptis-2.7.0-py3-none-any.whl.metadata (27 kB)
Collecting lxml>=4.5.2 (from ir-datasets->ranx)
  Downloading lxml-6.0.2-cp312-cp312-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl.metadata (3.6 kB)
Collecting trec-car-tools>=2.5.4 (from ir-datasets->ranx)
  Downloading trec_car_tools-2.6-py3-none-any.whl.metadata (640 bytes)
Collecting warc3-wet>=0.2.3 (from ir-datasets->ranx)
  Downloading warc3_wet-0.2.5-py3-none-any.whl.metadata (2.2 kB)
Collecting warc3-wet-clueweb09>=0.2.5 (from ir-datasets->ranx)
  Downloading warc3-wet-clueweb09-0.2.5.tar.gz (17 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting zlib-state>=0.1.3 (from ir-datasets->ranx)
  Downloading zlib_state-0.1.10-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.5 kB)
Collecting ijson>=3.1.3 (from ir-datasets->ranx)
  Downloading ijson-3.4.0.post0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (23 kB)
Collecting unlzw3>=0.2.1 (from ir-datasets->ranx)
  Downloading unlzw3-0.2.3-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->ranx) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->ranx) (2.19.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.12/dist-packages (from seaborn->ranx) (3.10.0)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets)
  Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (25.4.0)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets)
  Downloading frozenlist-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (20 kB)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (6.7.0)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets)
  Downloading propcache-0.4.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets)
  Downloading yarl-1.22.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (75 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.1/75.1 kB 6.7 MB/s eta 0:00:00
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.4.1->ir-datasets->ranx) (2.8)
Collecting lxml>=4.5.2 (from ir-datasets->ranx)
  Downloading lxml-5.4.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.5 kB)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->ranx) (0.1.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn->ranx) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn->ranx) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn->ranx) (4.61.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn->ranx) (1.4.9)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn->ranx) (3.2.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->ranx) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Collecting cbor>=1.0.0 (from trec-car-tools>=2.5.4->ir-datasets->ranx)
  Downloading cbor-1.0.0.tar.gz (20 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Downloading ranx-0.3.21-py3-none-any.whl (99 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.3/99.3 kB 7.7 MB/s eta 0:00:00
Downloading sentence_transformers-5.1.2-py3-none-any.whl (488 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 488.0/488.0 kB 22.4 MB/s eta 0:00:00
Downloading datasets-4.4.1-py3-none-any.whl (511 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.6/511.6 kB 43.3 MB/s eta 0:00:00
Downloading dill-0.4.0-py3-none-any.whl (119 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.7/119.7 kB 10.0 MB/s eta 0:00:00
Downloading fsspec-2025.10.0-py3-none-any.whl (200 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 201.0/201.0 kB 19.2 MB/s eta 0:00:00
Downloading multiprocess-0.70.18-py312-none-any.whl (150 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.3/150.3 kB 15.3 MB/s eta 0:00:00
Downloading cbor2-5.7.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (285 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 285.7/285.7 kB 25.6 MB/s eta 0:00:00
Downloading fastparquet-2024.11.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 81.3 MB/s eta 0:00:00
Downloading ir_datasets-0.5.11-py3-none-any.whl (866 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 866.1/866.1 kB 53.7 MB/s eta 0:00:00
Downloading lz4-4.4.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 81.0 MB/s eta 0:00:00
Downloading orjson-3.11.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (139 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.0/139.0 kB 14.5 MB/s eta 0:00:00
Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Downloading xxhash-3.6.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (193 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.9/193.9 kB 19.5 MB/s eta 0:00:00
Downloading aiohttp-3.13.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 19.7 MB/s eta 0:00:00
Downloading cramjam-2.11.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 100.0 MB/s eta 0:00:00
Downloading ijson-3.4.0.post0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (149 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.0/149.0 kB 12.6 MB/s eta 0:00:00
Downloading inscriptis-2.7.0-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 3.6 MB/s eta 0:00:00
Downloading lxml-5.4.0-cp312-cp312-manylinux_2_28_x86_64.whl (5.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 121.0 MB/s eta 0:00:00
Downloading trec_car_tools-2.6-py3-none-any.whl (8.4 kB)
Downloading unlzw3-0.2.3-py3-none-any.whl (6.7 kB)
Downloading warc3_wet-0.2.5-py3-none-any.whl (18 kB)
Downloading zlib_state-0.1.10-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (22 kB)
Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading frozenlist-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (242 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.4/242.4 kB 23.8 MB/s eta 0:00:00
Downloading propcache-0.4.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (221 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 221.6/221.6 kB 23.6 MB/s eta 0:00:00
Downloading yarl-1.22.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (377 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 377.3/377.3 kB 33.6 MB/s eta 0:00:00
Building wheels for collected packages: warc3-wet-clueweb09, cbor
  Building wheel for warc3-wet-clueweb09 (pyproject.toml) ... done
  Created wheel for warc3-wet-clueweb09: filename=warc3_wet_clueweb09-0.2.5-py3-none-any.whl size=18997 sha256=6ed53738f27fb4a3fc7199c97765200cd24e3d6ab16946a83c8b9fcf61944ec2
  Stored in directory: /root/.cache/pip/wheels/f6/85/c2/9f0f621def52a1d5db7d29984f81e45f9fb6dfeb1a4eb6e31c
  Building wheel for cbor (pyproject.toml) ... done
  Created wheel for cbor: filename=cbor-1.0.0-cp312-cp312-linux_x86_64.whl size=55064 sha256=97f1b5abbadc17043f286ca5db5474f21ede5e08e6e95cd607663eaf2dae0b87
  Stored in directory: /root/.cache/pip/wheels/44/3e/21/a739cbcc331a1ab45c326d6edbdac6118de4402f6076e30ff1
Successfully built warc3-wet-clueweb09 cbor
Installing collected packages: warc3-wet-clueweb09, warc3-wet, cbor, zlib-state, xxhash, unlzw3, trec-car-tools, tabulate, propcache, orjson, lz4, lxml, ijson, fsspec, frozenlist, dill, cramjam, cbor2, aiohappyeyeballs, yarl, multiprocess, inscriptis, aiosignal, ir-datasets, fastparquet, aiohttp, ranx, sentence-transformers, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.12.0
    Uninstalling fsspec-2025.12.0:
      Successfully uninstalled fsspec-2025.12.0
Successfully installed aiohappyeyeballs-2.6.1 aiohttp-3.13.2 aiosignal-1.4.0 cbor-1.0.0 cbor2-5.7.1 cramjam-2.11.0 datasets-4.4.1 dill-0.4.0 fastparquet-2024.11.0 frozenlist-1.8.0 fsspec-2025.10.0 ijson-3.4.0.post0 inscriptis-2.7.0 ir-datasets-0.5.11 lxml-5.4.0 lz4-4.4.5 multiprocess-0.70.18 orjson-3.11.5 propcache-0.4.1 ranx-0.3.21 sentence-transformers-5.1.2 tabulate-0.9.0 trec-car-tools-2.6 unlzw3-0.2.3 warc3-wet-0.2.5 warc3-wet-clueweb09-0.2.5 xxhash-3.6.0 yarl-1.22.0 zlib-state-0.1.10
WARNING: Skipping wandb as it is not installed.

/usr/local/lib/python3.12/dist-packages/jax/_src/cloud_tpu_init.py:86: UserWarning: Transparent hugepages are not enabled. TPU runtime startup and shutdown time should be significantly improved on TPU v5e and newer. If not already set, you may need to enable transparent hugepages in your VM image (sudo sh -c "echo always > /sys/kernel/mm/transparent_hugepage/enabled")
  warnings.warn(

In [ ]:
token = userdata.get('HF_TOKEN')
login(token=token)
print(whoami())

{'type': 'user', 'id': '663b5ba4347ccbda6657011c', 'name': 'davidpedidos', 'fullname': 'Garcia', 'isPro': False, 'avatarUrl': '/avatars/c7ec7e4f116a9a483fdbdb95dc009fc2.svg', 'orgs': [], 'auth': {'type': 'access_token', 'accessToken': {'displayName': 'colab_exe', 'role': 'fineGrained', 'createdAt': '2025-12-03T15:52:39.743Z', 'fineGrained': {'canReadGatedRepos': False, 'global': [], 'scoped': [{'entity': {'_id': '663b5ba4347ccbda6657011c', 'type': 'user', 'name': 'davidpedidos'}, 'permissions': []}]}}}}

In [ ]:
# Configuración básica
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
today = time.strftime("%Y-%m-%d")

In [ ]:
def set_directories():
  project_dir = Path(__name__).resolve().parents[1]
  project_dir = project_dir / 'content' / 'TalentCLEF-TaskA'
  date_dir = project_dir.parent / 'output' / today
  date_dir.mkdir(parents=True, exist_ok=True)

  # Crear subdirectorio incremental por ejecución (001, 002, ...)
  exec_dirs = sorted([d for d in date_dir.iterdir() if d.is_dir() and d.name.isdigit() and len(d.name) == 3])
  if exec_dirs and not any(exec_dirs[-1].iterdir()):
      output_dir = exec_dirs[-1]
  else:
      next_id = int(exec_dirs[-1].name) + 1 if exec_dirs else 1
      output_dir = date_dir / f"{next_id:03d}"
      output_dir.mkdir(exist_ok=True)

  return project_dir, output_dir

project_dir, output_dir = set_directories()

In [ ]:
!git clone https://github.com/davidgc14/TalentCLEF-TaskA.git
!cp ./TalentCLEF-TaskA/src/output/ranking_spanish_validation.csv {output_dir.parent.parent}
!rm -r sample_data/

Cloning into 'TalentCLEF-TaskA'...
remote: Enumerating objects: 870, done.
remote: Counting objects: 100% (656/656), done.
remote: Compressing objects: 100% (333/333), done.
remote: Total 870 (delta 381), reused 577 (delta 309), pack-reused 214 (from 1)
Receiving objects: 100% (870/870), 58.18 MiB | 47.78 MiB/s, done.
Resolving deltas: 100% (448/448), done.

## Evaluation functions

In [ ]:
def load_qrels(qrels_path):
    """
    Loads the qrels file (TREC format: q_id, iter, doc_id, rel)
    and converts it to a Qrels object.
    """
    qrels_df = pd.read_csv(qrels_path, sep="\t", header=None,
                           names=["q_id", "iter", "doc_id", "rel"],
                           dtype={"q_id": str, "doc_id": str, "rel":int})

    return Qrels.from_df(qrels_df, q_id_col="q_id", doc_id_col="doc_id", score_col="rel")

def load_run(run_path):
    """
    Loads the run file (TREC format: q_id, Q0, doc_id, rank, score, [tag])
    and converts it to a Run object.
    """
    run_df = pd.read_csv(run_path, sep=r"\s+", header=None)

    # Assign column names based on the number of columns
    if run_df.shape[1] == 5:
        run_df.columns = ["q_id", "Q0", "doc_id", "rank", "score"]
    elif run_df.shape[1] >= 6:
        run_df.columns = ["q_id", "Q0", "doc_id", "rank", "score", "tag"]
    else:
        raise ValueError("The run file does not have the expected format.")

    run_df["q_id"] = run_df.q_id.astype(str)
    run_df["doc_id"] = run_df.doc_id.astype(str)
    return Run.from_df(run_df, q_id_col="q_id", doc_id_col="doc_id", score_col="score")

def evaluate_run(qrels_path, run_path):
    """Evalúa un run y devuelve los resultados como dict."""
    qrels = load_qrels(qrels_path)
    run = load_run(run_path)
    metrics = ["map", "mrr", "ndcg", "precision@5", "precision@10", "precision@100"]
    return evaluate(qrels, run, metrics)

In [ ]:

# ========================
# DATA LOADING AND ENCODING
# ========================

def load_spanish_data(data_dir):
    """Load queries and corpus elements from Spanish data directory."""
    queries_path = data_dir / "queries"
    corpus_elements_path = data_dir / "corpus_elements"

    queries = pd.read_csv(queries_path, sep="\t")
    corpus_elements = pd.read_csv(corpus_elements_path, sep="\t")

    return (
        queries.q_id.to_list(),
        queries.jobtitle.to_list(),
        corpus_elements.c_id.to_list(),
        corpus_elements.jobtitle.to_list(),
    )


def encode_data(model, queries_texts, corpus_texts, model_name, device):
    """Encode queries and corpus using the model."""
    print('Encoding data:', model_name, 'on device:', device)
    query_embeddings = model.encode(queries_texts, convert_to_tensor=True, show_progress_bar=False, device=device)
    corpus_embeddings = model.encode(corpus_texts, convert_to_tensor=True, show_progress_bar=False, device=device)
    return query_embeddings, corpus_embeddings


def calculate_similarities_and_format_results(query_embeddings, corpus_embeddings, queries_ids, corpus_ids, model_name):
    """Calculate cosine similarities and format results in TREC format."""
    print('Calculating similarities and preparing results...')
    similarities = util.cos_sim(query_embeddings, corpus_embeddings).cpu().numpy()

    results = []
    for q_idx, q_id in enumerate(queries_ids):
        sorted_indices = np.argsort(-similarities[q_idx])  # Orden descendente
        for rank, c_idx in enumerate(sorted_indices):
            doc_id = corpus_ids[c_idx]
            score = similarities[q_idx, c_idx]
            results.append(f"{str(q_id)} Q0 {str(doc_id)} {rank+1} {score:.4f} {model_name}")
    return results


def run_evaluation_temp(qrels_path, results, model_name):
    """Run evaluation using temporary file without saving."""
    print('Evaluating Spanish monolingual performance...')

    # Crear archivo temporal
    with tempfile.NamedTemporaryFile(mode='w', suffix='.trec', delete=False, encoding='utf-8') as tmp_file:
        tmp_file.write("\n".join(results))
        tmp_path = tmp_file.name

    try:
        evaluation_results = evaluate_run(qrels_path, tmp_path)
    finally:
        # Eliminar archivo temporal
        os.unlink(tmp_path)

    return evaluation_results


def get_model_name(model):
    """Extract model name from the model object."""
    model_name = model[0].auto_model.config._name_or_path
    return model_name.split("/")[-1]


# ========================
# EVALUATION FUNCTION
# ========================

def spanish_monolingual_evaluation(model, device, source):
    """Evaluate model performance on Spanish monolingual data."""
    data_dir = project_dir / 'data' / source / 'spanish'
    qrels_path = data_dir / "qrels.tsv"

    print('Loading Spanish data...')
    queries_ids, queries_texts, corpus_ids, corpus_texts = load_spanish_data(data_dir)
    model_name = get_model_name(model)

    query_embeddings, corpus_embeddings = encode_data(model, queries_texts, corpus_texts, model_name, device)
    results = calculate_similarities_and_format_results(query_embeddings, corpus_embeddings, queries_ids, corpus_ids, model_name)

    evaluation_results = run_evaluation_temp(qrels_path, results, model_name)
    print('Spanish evaluation completed')
    return evaluation_results


# ========================
# SAVING RESULTS
# ========================

def save_spanish_results(evaluation_results, model_name, nickname, source):
    """Save Spanish monolingual evaluation results to JSON file."""
    print("Saving Spanish evaluation results...")

    json_path = output_dir / "results_spanish_monolingual.json"

    results_data = {
        "metadata": {
            "type": "spanish_monolingual",
            "model_name": model_name,
            "nickname": nickname,
            "source": source,
            "timestamp": today
        },
        "results": evaluation_results
    }

    with open(json_path, "w", encoding="utf-8") as jf:
        json.dump(results_data, jf, indent=2, ensure_ascii=False)

    print(f"Saved Spanish results to {json_path}")


# ========================
# RANKING
# ========================

def update_spanish_ranking(map_score, model_name, nickname, source):
    """Update Spanish-specific ranking CSV file with current execution results."""
    print("Updating Spanish ranking file...")

    ranking_file = output_dir.parent.parent / f"ranking_spanish_{source}.csv"
    execution_id = output_dir.name

    new_record = {
        'timestamp': today,
        'execution_id': execution_id,
        'model_name': model_name,
        'model_alias': nickname,
        'map_es_es': map_score
    }

    if ranking_file.exists():
        df = pd.read_csv(ranking_file)
    else:
        df = pd.DataFrame(columns=['timestamp', 'execution_id', 'model_name', 'model_alias', 'map_es_es'])

    # Double check for existing identical record
    comparison_cols = ['model_name', 'model_alias', 'map_es_es']

    if not df.empty:
        new_record_comparison = {k: new_record.get(k, np.nan) for k in comparison_cols}
        existing_records = df[comparison_cols].to_dict('records')

        for existing in existing_records:
            if all(abs(existing.get(k, np.nan) - new_record_comparison.get(k, np.nan)) < 1e-4
                   if isinstance(new_record_comparison.get(k), (float, int)) and not np.isnan(new_record_comparison.get(k, np.nan))
                   else existing.get(k) == new_record_comparison.get(k)
                   for k in comparison_cols):
                print("Ya existe un registro idéntico en el ranking español. No se agregará el nuevo registro.")
                return

    # Evitar warning de pandas con DataFrame vacío
    if df.empty:
        df = pd.DataFrame([new_record])
    else:
        df = pd.concat([df, pd.DataFrame([new_record])], ignore_index=True)

    df = df.sort_values('map_es_es', ascending=False).reset_index(drop=True)
    df.to_csv(ranking_file, index=False)

    print(f"Ranking español actualizado en {ranking_file}")


# ========================
# MAIN PIPELINE
# ========================

def run_spanish_evaluation(model_name, nickname, device, source):
    """Run complete Spanish monolingual evaluation pipeline."""
    model = SentenceTransformer(model_name, device=device)

    evaluation_results = spanish_monolingual_evaluation(model, device, source)
    save_spanish_results(evaluation_results, model_name, nickname, source)

    map_score = evaluation_results.get('map', np.nan)
    update_spanish_ranking(map_score, model_name, nickname, source)

    print(f"\n{'='*50}")
    print(f"Evaluación completada para {model_name}")
    print(f"MAP español-español: {map_score:.4f}")
    print(f"{'='*50}\n\n")

# Training path

## Config

In [ ]:
MODEL_NAME = 'paraphrase-multilingual-mpnet-base-v2'
BATCH_SIZE = 64
EPOCHS = 30
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

# Rutas de salida para el entrenamiento Hugging Face
model_output_path = output_dir / 'finetuned_models' / MODEL_NAME
best_model_path = model_output_path / 'best_model'
logs_path = model_output_path / 'logs'

print(f"Directorio de proyecto: {project_dir}")
print(f"Guardando outputs en: {model_output_path}")

Directorio de proyecto: /content/TalentCLEF-TaskA
Guardando outputs en: /content/output/2025-11-26/001/finetuned_models/paraphrase-multilingual-mpnet-base-v2

## Data preparation

### Training data

In [ ]:
def normalize_text(text):
    if pd.isna(text): return ""
    text = str(text).lower().strip()
    text = unicodedata.normalize('NFC', text)
    # Reemplazar puntuación por espacio para no pegar palabras
    text = re.sub(r'[^\w\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

In [ ]:
training_file = project_dir / 'data' / 'training' / 'spanish' / 'taskA_training_es.tsv'

train_df = pd.read_csv(training_file, sep='\t', header=None)
train_df.columns = ['family_id', 'id', 'jobtitle_1', 'jobtitle_2']

In [ ]:
expanded = []
for _, row in train_df.iterrows():
    jt1 = row['jobtitle_1']
    jt2 = row['jobtitle_2']

    # Obtener opciones para cada columna
    opts1 = [x.strip() for x in jt1.split('/')]
    opts2 = [x.strip() for x in jt2.split('/')]

    # Crear combinaciones A × B
    for a, b in itertools.product(opts1, opts2):
        if a != b:
            expanded.append({
                't1': a,
                't2': b
            })

df_expanded = pd.DataFrame(expanded)

In [ ]:
# Normalización
df_expanded['t1'] = df_expanded['t1'].apply(normalize_text)
df_expanded['t2'] = df_expanded['t2'].apply(normalize_text)

# Eliminar duplicados (considerando pares desordenados)
# Creamos una columna temporal 'key' para filtrar
df_expanded['key'] = df_expanded.apply(lambda x: frozenset([x['t1'], x['t2']]), axis=1)
df_unique = df_expanded.drop_duplicates(subset='key').drop(columns=['key'])

# Filtrar vacíos
df_unique = df_unique[(df_unique['t1'] != "") & (df_unique['t2'] != "")]

# Convertir las columnas a string ANTES de crear el Dataset
df_unique['t1'] = df_unique['t1'].astype(str)
df_unique['t2'] = df_unique['t2'].astype(str)

# Resetear índice y crear el Dataset sin preservar el índice de pandas
df_unique = df_unique.reset_index(drop=True)
train_df_for_ds = df_unique[['t1', 't2']].rename(columns={'t1': 'sentence_1', 't2': 'sentence_2'})

In [ ]:
train_dataset = Dataset.from_pandas(train_df_for_ds, preserve_index=False)
print(f"Total de parejas en entrenamiento: {len(train_dataset)}")

Total de parejas en entrenamiento: 17855

### Validation data

In [ ]:
validation_dir = project_dir / 'data' / 'validation' / 'spanish'

corpus_val = pd.read_csv(validation_dir / 'corpus_elements', sep='\t')
queries_val = pd.read_csv(validation_dir / 'queries', sep='\t')
qrels_val = pd.read_csv(validation_dir / 'qrels.tsv', sep='\t', header=None)
qrels_val.columns = ['q_id', 'iter', 'doc_id', 'rel']

In [ ]:
# Diccionarios normalizados
corpus_dict = {str(row.iloc[0]): normalize_text(row.iloc[1]) for _, row in corpus_val.iterrows()}
queries_dict = {str(row.iloc[0]): normalize_text(row.iloc[1]) for _, row in queries_val.iterrows()}

# Construir dataset de pares positivos para calcular la Loss de validación
val_pairs = []
for _, row in qrels_val.iterrows():
    q_id = str(row.iloc[0])
    c_id = str(row.iloc[2])
    score = int(row.iloc[3])

    if score > 0 and q_id in queries_dict and c_id in corpus_dict:
        val_pairs.append({
            'sentence_1': queries_dict[q_id],
            'sentence_2': corpus_dict[c_id]
        })

In [ ]:
val_dataset = Dataset.from_list(val_pairs)
print(f"Pares de validación para Early Stopping: {len(val_dataset)}")

Pares de validación para Early Stopping: 7579

## Model preparation

In [ ]:
# Cargar modelo
model = SentenceTransformer(MODEL_NAME, device=DEVICE)

# Definir función de pérdida
# MultipleNegativesRankingLoss es estándar para pares (Anchor, Positive)
train_loss = losses.MultipleNegativesRankingLoss(model=model)

# Definir argumentos de entrenamiento (usando la clase nativa de SentenceTransformers/HF)
args = SentenceTransformerTrainingArguments(
    output_dir=str(model_output_path),
    num_train_epochs=EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    learning_rate=2e-5,
    warmup_ratio=0.1,
    fp16=(DEVICE == 'cuda'),  # Usar precisión mixta si hay GPU
    eval_strategy="epoch",    # Evaluar al final de cada época
    save_strategy="epoch",    # Guardar checkpoint al final de cada época
    load_best_model_at_end=True, # Cargar el mejor modelo al terminar (CRUCIAL para Early Stopping)
    metric_for_best_model="eval_loss",
    save_total_limit=2,       # No llenar el disco con checkpoints
    logging_steps=50,
    batch_sampler=BatchSamplers.NO_DUPLICATES # Evitar duplicados en batch para MNRLoss
)

early_stopping_callback = EarlyStoppingCallback(
    early_stopping_patience=5,  # Número de épocas sin mejora antes de detener
    early_stopping_threshold=0.001 # Umbral mínimo de mejora
)

# Inicializar Trainer con EarlyStoppingCallback
trainer = SentenceTransformerTrainer(
    model=model,
    args=args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    loss=train_loss,
    callbacks=[early_stopping_callback]
)

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

## Training model

In [ ]:
print("\n--- Comenzando entrenamiento... ---")
trainer.train()
print("\n--- Entrenamiento finalizado ---")

--- Comenzando entrenamiento... ---

--- Entrenamiento finalizado ---

In [ ]:
print(f"Guardando mejor modelo en: {best_model_path}")
model.save(str(best_model_path))

final_model = SentenceTransformer(str(best_model_path), device=DEVICE)

Guardando mejor modelo en: /content/output/2025-11-26/001/finetuned_models/paraphrase-multilingual-mpnet-base-v2/best_model

## Final evaluation

In [ ]:

# Ejecutar tu evaluación personalizada (si existe la función en el contexto)
# Asumimos que run_spanish_evaluation estaba definida o se importó.
# Si no, simplemente imprimimos confirmación.

print("\nModelo cargado y listo para inferencia.")
# Ejemplo de uso rápido:
# embeddings = final_model.encode(["ingeniero de datos", "data engineer"])
# sim = util.cos_sim(embeddings[0], embeddings[1])
# print(f"Similitud de prueba: {sim.item()}")

Modelo cargado y listo para inferencia.

In [ ]:
spanish_monolingual_evaluation(final_model, DEVICE, 'validation')

Loading Spanish data...
Encoding data: best_model on device: cuda

Batches:   0%|          | 0/6 [00:00<?, ?it/s]

Batches:   0%|          | 0/146 [00:00<?, ?it/s]

Calculating similarities and preparing results...
Evaluating Spanish monolingual performance...

/usr/local/lib/python3.12/dist-packages/ranx/metrics/average_precision.py:49: NumbaTypeSafetyWarning: unsafe cast from uint64 to int64. Precision may be lost.
  scores[i] = _average_precision(qrels[i], run[i], k, rel_lvl)

Spanish evaluation completed

{'map': np.float64(0.45862232062435015),
 'mrr': np.float64(0.5563063063063063),
 'ndcg': np.float64(0.745120995023976),
 'precision@5': np.float64(0.6605405405405405),
 'precision@10': np.float64(0.6545945945945946),
 'precision@100': np.float64(0.24421621621621625)}

In [ ]:
#comprimir carpeta del best_model
shutil.make_archive(best_model_path, 'zip', project_dir)

'/content/output/2025-11-26/001/finetuned_models/paraphrase-multilingual-mpnet-base-v2/best_model.zip'

In [ ]:
best_model_path

PosixPath('/content/output/2025-11-26/001/finetuned_models/paraphrase-multilingual-mpnet-base-v2/best_model')

# Massive Experimentation

## Hugging face iteration

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
source = 'validation'

models = list(list_models(
    pipeline_tag="sentence-similarity",
    library=["sentence-transformers", "transformers"],
    language="es"
))

models = sorted(models, key=lambda x: x.id)

NameError: name 'torch' is not defined

In [ ]:
df = pd.DataFrame(columns=['model_name', 'num_params', 'languages', 'map_es_es', 'mrr', 'ndcg', 'p@5', 'p@10', 'p@100'])
errors = []
for m in models:
  info = model_info(m.id)
  langs = info.cardData.get("languages") or info.cardData.get("language")
  mode = 'multilingual' if len(langs) > 1 else 'monolingual'

  try:
    model = SentenceTransformer(m.id, device=device, trust_remote_code=True)
    evaluation_results = spanish_monolingual_evaluation(model, device, source)
  except:
    errors.append(m.id)
    continue

  num_params = sum(p.numel() for p in model.parameters())

  df = pd.concat([df, pd.DataFrame([{
        'model_name': m.id,
        'num_params': num_params,
        'languages': mode,
        'map_es_es': evaluation_results.get('map', np.nan),
        'mrr': evaluation_results.get('mrr', np.nan),
        'ndcg': evaluation_results.get('ndcg', np.nan),
        'p@5': evaluation_results.get('precision@5', np.nan),
        'p@10': evaluation_results.get('precision@10', np.nan),
        'p@100': evaluation_results.get('precision@100', np.nan)
  }])], ignore_index=True)


df = df.sort_values('map_es_es', ascending=False).reset_index(drop=True)

In [ ]:
df

In [ ]:
df.to_csv(output_dir / 'hf_evaluation_results.csv', index=False)

# los modelos que no se han podido ejecutar es porque son cuantizaciones de modelos mayores que si se han ejecutado
with open(output_dir / "hf_errors.txt", "w") as archivo:
    for item in errors:
        archivo.write(f"{item}\n")

## Other models from MTEB leaderboard

In [ ]:
model_name = 'McGill-NLP/LLM2Vec-Mistral-7B-Instruct-v2-mntp-supervised'

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
source = 'validation'

model = SentenceTransformer(model_name, device=device, trust_remote_code=True)
evaluation_results = spanish_monolingual_evaluation(model, device, source)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
WARNING:sentence_transformers.SentenceTransformer:No sentence-transformers model found with name McGill-NLP/LLM2Vec-Mistral-7B-Instruct-v2-mntp-supervised. Creating a new one with mean pooling.

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

In [ ]:
info = model_info(model_name)
langs = info.cardData.get("languages") or info.cardData.get("language")
mode = 'multilingual' if len(langs) > 1 else 'monolingual'
num_params = sum(p.numel() for p in model.parameters())

print(f"Model name: {model_name}")
print(f"Languages: {mode}")
print(f"Number of parameters: {num_params}")

print(evaluation_results)

model

## MTEB models itteration

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
source = 'validation'

with open(project_dir / 'models' / 'results' / 'mteb' / 'mteb_models_list.txt', 'r') as file:
    models = file.read().splitlines()

models = sorted(models, reverse=True)

df = pd.DataFrame(columns=['model_name', 'num_params', 'languages', 'map_es_es', 'mrr', 'ndcg', 'p@5', 'p@10', 'p@100'])
errors = []

In [ ]:
df = pd.read_csv('/content/mteb_evaluation_results_checkpoint.csv')

with open('/content/mteb_errors_checkpoint.txt', "r") as archivo:
    errors = [line.strip() for line in archivo.readlines()]

In [ ]:
df

,model_name,num_params,languages,map_es_es,mrr,ndcg,p@5,p@10,p@100
0,thenlper/gte-small,33360000,monolingual,0.304450,0.535157,0.645663,0.605405,0.537297,0.171730
1,thenlper/gte-large,335141888,monolingual,0.341373,0.544084,0.672224,0.614054,0.569189,0.187946
2,thenlper/gte-base,109482240,monolingual,0.319907,0.546937,0.657480,0.602162,0.549189,0.179405
3,sentence-transformers/all-mpnet-base-v2,109486464,multilingual,0.263311,0.538492,0.622412,0.561081,0.493514,0.150541
4,sentence-transformers/all-MiniLM-L6-v2,22713216,multilingual,0.283830,0.539444,0.630327,0.572973,0.525946,0.158216
5,sentence-transformers/all-MiniLM-L12-v2,33360000,multilingual,0.291990,0.534586,0.636105,0.576216,0.521622,0.166378
6,sdadas/mmlw-roberta-large,434961408,multilingual,0.267101,0.552162,0.627704,0.569730,0.497297,0.150595
7,sentence-transformers/paraphrase-multilingual-...,117653760,multilingual,0.376560,0.541937,0.697857,0.607568,0.572973,0.211784
8,sdadas/mmlw-e5-large,559890432,multilingual,0.327969,0.548174,0.665108,0.588108,0.533514,0.179838
9,sdadas/mmlw-e5-base,278043648,multilingual,0.308906,0.530482,0.652663,0.582703,0.534595,0.171730

In [ ]:
errors

['sentence-transformers/static-similarity-mrl-multilingual-v1',
 'parasail-ai/GritLM-7B-vllm']

In [ ]:
for index, model_name in enumerate(models):

  if model_name in df.model_name.values or model_name in errors:
    continue

  if index == 0:
    print('Comenzamos desde el principio')
  else:
    print(f'Continuamos con iteracion {index}.')

  print(f'Cargando modelo {model_name}')

  try:
    info = model_info(model_name)
    langs = info.cardData.get("languages") or info.cardData.get("language")
    mode = 'multilingual' if len(langs) > 1 else 'monolingual'
  except:
    mode = 'unknown'

  try:
    # descarga local para separar los dos procesos de descarga y carga
    local_dir = snapshot_download(repo_id=model_name, cache_dir="/content/hf_cache", use_auth_token=True, resume_download=True, force_download=False, local_files_only=False)
    model = SentenceTransformer(local_dir, device=device, trust_remote_code=True)
    evaluation_results = spanish_monolingual_evaluation(model, device, source)
  except Exception as e:
    print(f'Error al cargar modelo {model_name}: {e}')
    errors.append(model_name)
    continue

  num_params = sum(p.numel() for p in model.parameters())

  df = pd.concat([df, pd.DataFrame([{
        'model_name': model_name,
        'num_params': num_params,
        'languages': mode,
        'map_es_es': evaluation_results.get('map', np.nan),
        'mrr': evaluation_results.get('mrr', np.nan),
        'ndcg': evaluation_results.get('ndcg', np.nan),
        'p@5': evaluation_results.get('precision@5', np.nan),
        'p@10': evaluation_results.get('precision@10', np.nan),
        'p@100': evaluation_results.get('precision@100', np.nan)
  }])], ignore_index=True)


  if index % 1 == 0:
    df.to_csv(output_dir / 'mteb_evaluation_results_checkpoint.csv', index=False)
    with open(output_dir / "mteb_errors_checkpoint.txt", "w") as archivo:
        for item in errors:
            archivo.write(f"{item}\n")

    print('==========================================')
    print(f'Checkpoint en iteracion {index}')
    print('==========================================')

Continuamos con iteracion 12.
Cargando modelo nvidia/NV-Embed-v2

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Fetching 19 files:   0%|          | 0/19 [00:00<?, ?it/s]

config.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/298 [00:00<?, ?B/s]

configuration_nvembed.py: 0.00B [00:00, ?B/s]

instructions.json: 0.00B [00:00, ?B/s]

.gitattributes: 0.00B [00:00, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/171 [00:00<?, ?B/s]

model-00001-of-00004.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

model-00002-of-00004.safetensors:   0%|          | 0.00/4.92G [00:00<?, ?B/s]

model-00003-of-00004.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

model-00004-of-00004.safetensors:   0%|          | 0.00/789M [00:00<?, ?B/s]

modeling_nvembed.py: 0.00B [00:00, ?B/s]

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/55.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/551 [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/493k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/997 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/997 [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/493k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/551 [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

In [ ]:
df = df.sort_values('map_es_es', ascending=False).reset_index(drop=True)
df.to_csv(output_dir / 'mteb_evaluation_results.csv', index=False)

# los modelos que no se han podido ejecutar es porque son cuantizaciones de modelos mayores que si se han ejecutado
with open(output_dir / "mteb_errors.txt", "w") as archivo:
    for item in errors:
        archivo.write(f"{item}\n")

In [ ]:
df

In [ ]:
errors

## MTEB Models Iteration con control de RAM

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
source = 'validation'

with open(project_dir / 'models' / 'results' / 'mteb' / 'mteb_models_list.txt', 'r') as file:
    models = file.read().splitlines()

models = sorted(models, reverse=True)

df = pd.DataFrame(columns=['model_name', 'num_params', 'languages', 'map_es_es', 'mrr', 'ndcg', 'p@5', 'p@10', 'p@100'])
reported_errors = pd.DataFrame(columns=['model_name', 'error'])

errors = []

In [ ]:
df = pd.read_csv('/content/mteb_evaluation_results_checkpoint.csv')
reported_errors = pd.read_csv('/content/mteb_reported_errors_checkpoint.csv')

combined = pd.read_csv(project_dir / 'models' / 'results' / 'temp_combined_evaluation.csv')

with open('/content/mteb_errors_checkpoint.txt', "r") as archivo:
    errors = [line.strip() for line in archivo.readlines()]

In [ ]:
df

,model_name,num_params,languages,map_es_es,mrr,ndcg,p@5,p@10,p@100
0,nvidia/llama-embed-nemotron-8b,7504924672,multilingual,0.226806,0.525526,0.604436,0.496216,0.418378,0.135405
1,thenlper/gte-small,33360000,monolingual,0.304450,0.535157,0.645663,0.605405,0.537297,0.171730
2,thenlper/gte-large,335141888,monolingual,0.341373,0.544084,0.672224,0.614054,0.569189,0.187946
3,thenlper/gte-base,109482240,monolingual,0.319907,0.546937,0.657480,0.602162,0.549189,0.179405
4,sentence-transformers/all-mpnet-base-v2,109486464,multilingual,0.263311,0.538492,0.622412,0.561081,0.493514,0.150541
5,sentence-transformers/all-MiniLM-L6-v2,22713216,multilingual,0.283830,0.539444,0.630327,0.572973,0.525946,0.158216
6,sentence-transformers/all-MiniLM-L12-v2,33360000,multilingual,0.291990,0.534586,0.636105,0.576216,0.521622,0.166378
7,sdadas/mmlw-roberta-large,434961408,multilingual,0.267101,0.552162,0.627704,0.569730,0.497297,0.150595
8,sentence-transformers/paraphrase-multilingual-...,117653760,multilingual,0.376560,0.541937,0.697857,0.607568,0.572973,0.211784
9,sdadas/mmlw-e5-large,559890432,multilingual,0.327969,0.548174,0.665108,0.588108,0.533514,0.179838
10,sdadas/mmlw-e5-base,278043648,multilingual,0.308906,0.530482,0.652663,0.582703,0.534595,0.171730
11,nomic-ai/nomic-embed-text-v1.5,136731648,monolingual,0.322525,0.550360,0.659815,0.630270,0.572973,0.173027
12,mixedbread-ai/mxbai-embed-large-v1,335141888,monolingual,0.331692,0.539820,0.666157,0.602162,0.555676,0.182919
13,manu/sentence_croissant_alpha_v0.4,1279887360,multilingual,0.343574,0.528874,0.676714,0.597838,0.541622,0.194108
14,manu/sentence_croissant_alpha_v0.3,1279887360,multilingual,0.360058,0.535285,0.688281,0.607568,0.564324,0.201189
15,manu/sentence_croissant_alpha_v0.2,1279887360,multilingual,0.305044,0.529615,0.654692,0.580541,0.506486,0.177081
16,jinaai/jina-embedding-s-en-v1,35330816,multilingual,0.242359,0.543694,0.610189,0.560000,0.490811,0.142000
17,jinaai/jina-embedding-b-en-v1,109628544,multilingual,0.273815,0.547979,0.630361,0.569730,0.516216,0.153568
18,intfloat/e5-small-v2,33360000,monolingual,0.277987,0.539009,0.631266,0.567568,0.515676,0.164216
19,infly/inf-retriever-v1-1.5b,1543268864,multilingual,0.347356,0.557838,0.687668,0.611892,0.572973,0.197027
20,ibm-granite/granite-embedding-30m-english,30295296,monolingual,0.273434,0.533994,0.629076,0.570811,0.520541,0.161351
21,ibm-granite/granite-embedding-125m-english,124645632,monolingual,0.280153,0.543829,0.635717,0.581622,0.515135,0.164919
22,deepvk/USER-bge-m3,359026688,monolingual,0.303490,0.540739,0.661728,0.579459,0.524865,0.178865
23,chienpham/sts-multilingual-mpnet-base-v2,278043648,unknown,0.443588,0.551532,0.734145,0.654054,0.636757,0.236757
24,brahmairesearch/slx-v0.1,22713216,multilingual,0.283830,0.539444,0.630327,0.572973,0.525946,0.158216
25,avsolatorio/GIST-small-Embedding-v0,33360000,monolingual,0.292113,0.545568,0.637250,0.570811,0.520541,0.167514
26,avsolatorio/GIST-large-Embedding-v0,335141888,monolingual,0.337014,0.545195,0.668900,0.608649,0.568649,0.184811
27,avsolatorio/GIST-all-MiniLM-L6-v2,22713216,monolingual,0.291215,0.540562,0.633126,0.579459,0.535676,0.163243
28,avsolatorio/GIST-Embedding-v0,109482240,monolingual,0.316977,0.554655,0.654813,0.595676,0.541622,0.176054
29,abhinand/MedEmbed-small-v0.1,33360000,multilingual,0.292104,0.544657,0.637068,0.584865,0.526486,0.165243
30,WhereIsAI/UAE-Large-V1,335141888,monolingual,0.328295,0.550901,0.664467,0.588108,0.553514,0.181135
31,Snowflake/snowflake-arctic-embed-s,33212160,unknown,0.274037,0.545671,0.624747,0.578378,0.519459,0.160054
32,Snowflake/snowflake-arctic-embed-m-v1.5,108891648,unknown,0.300188,0.544272,0.646835,0.592432,0.530270,0.168162
33,Snowflake/snowflake-arctic-embed-m-long,136731648,unknown,0.297339,0.538696,0.643176,0.593514,0.542162,0.165297
34,Snowflake/snowflake-arctic-embed-l-v2.0,567754752,multilingual,0.383312,0.546898,0.707347,0.625946,0.601081,0.215946
35,Qwen/Qwen3-Embedding-0.6B,595776512,unknown,0.371771,0.550776,0.700149,0.616216,0.571892,0.211676
36,OrdalieTech/Solon-embeddings-large-0.1,559890432,monolingual,0.357746,0.546757,0.693753,0.598919,0.574054,0.205730
37,Omartificial-Intelligence-Space/Arabic-labse-M...,471517440,monolingual,0.388832,0.538960,0.709853,0.625946,0.588649,0.214649
38,Omartificial-Intelligence-Space/Arabic-all-nli...,278043648,monolingual,0.401266,0.554414,0.714717,0.635676,0.603243,0.219081
39,Omartificial-Intelligence-Space/Arabic-MiniLM-...,117653760,monolingual,0.370755,0.548559,0.695512,0.602162,0.575676,0.206000
40,Mihaiii/Ivysaur,22713216,unknown,0.298813,0.541377,0.640398,0.592432,0.547568,0.168324
41,Linq-AI-Research/Linq-Embed-Mistral,7110660096,monolingual,0.409481,0.546126,0.721602,0.629189,0.608649,0.230324
42,Lajavaness/bilingual-embedding-small,117653760,multilingual,0.405341,0.550450,0.718434,0.630270,0.604324,0.217081
43,Lajavaness/bilingual-embedding-large,559890432,multilingual,0.449344,0.546847,0.744623,0.650811,0.637838,0.244865
44,Lajavaness/bilingual-embedding-base,278043648,unknown,0.382731,0.544505,0.705589,0.597838,0.578919,0.219135
45,HIT-TMG/KaLM-embedding-multilingual-mini-v1,494032768,unknown,0.370517,0.538649,0.698484,0.601081,0.565946,0.204378
46,HIT-TMG/KaLM-embedding-multilingual-mini-instr...,494032768,unknown,0.368127,0.537297,0.699045,0.602162,0.564865,0.204865
47,BAAI/bge-small-en-v1.5,33360000,monolingual,0.287693,0.542405,0.635168,0.583784,0.516216,0.166054
48,BAAI/bge-m3,567754752,unknown,0.305227,0.533945,0.664734,0.570811,0.518378,0.179676
49,BAAI/bge-large-en-v1.5,335141888,monolingual,0.321234,0.541622,0.660202,0.591351,0.543784,0.178595
50,BAAI/bge-base-en-v1.5,109482240,monolingual,0.301245,0.539681,0.644459,0.591351,0.528649,0.170973

In [ ]:
errors

['sentence-transformers/static-similarity-mrl-multilingual-v1',
 'parasail-ai/GritLM-7B-vllm',
 'nvidia/NV-Embed-v2',
 '',
 'nvidia/NV-Embed-v1',
 'nan',
 'minishlab/potion-multilingual-128M',
 'jinaai/jina-embeddings-v4',
 'jinaai/jina-embeddings-v3',
 'intfloat/multilingual-e5-small',
 'intfloat/multilingual-e5-large-instruct',
 'intfloat/multilingual-e5-large',
 'intfloat/multilingual-e5-base',
 'intfloat/e5-mistral-7b-instruct',
 'intfloat/e5-large-v2',
 'intfloat/e5-base-v2',
 'infly/inf-retriever-v1',
 'google/embeddinggemma-300m',
 'gandolfi/bge-m3-custom-fr-Q4_K_M-GGUF',
 'bartowski/granite-embedding-107m-multilingual-GGUF',
 'avsolatorio/NoInstruct-small-Embedding-v0',
 'Snowflake/snowflake-arctic-embed-m-v2.0',
 'Salesforce/SFR-Embedding-Mistral',
 'Salesforce/SFR-Embedding-2_R',
 'Qwen/Qwen3-Embedding-8B',
 'Qwen/Qwen3-Embedding-4B',
 'NovaSearch/stella_en_400M_v5',
 'NovaSearch/stella_en_1.5B_v5',
 'NovaSearch/jasper_en_vision_language_v1']

In [ ]:
# Configuración
RAM_THRESHOLD = 90  # Ajusta según tu entorno (80-85 para Colab)
VRAM_THRESHOLD = 95  # Umbral para VRAM (puede ser más alto que RAM)
RAM_CHECK_INTERVAL = 0.3  # Verificar cada 0.5 segundos

def get_ram_usage():
    """Retorna el porcentaje de RAM utilizado"""
    return psutil.virtual_memory().percent

def get_vram_usage():
    """Retorna el porcentaje de VRAM utilizado"""
    if torch.cuda.is_available():
        total_vram = torch.cuda.get_device_properties(0).total_memory
        allocated_vram = torch.cuda.memory_allocated(0)
        return (allocated_vram / total_vram) * 100
    return 0

def get_vram_gb():
    """Retorna VRAM usado en GB"""
    if torch.cuda.is_available():
        return torch.cuda.memory_allocated(0) / 1024**3
    return 0

def clear_memory():
    """Libera memoria de forma agresiva"""
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.synchronize()

def load_model_with_monitoring(model_name, local_dir, device, ram_threshold=85, vram_threshold=90, check_interval=2.0):
    """
    Carga un modelo monitoreando RAM y VRAM periódicamente durante la carga.

    Args:
        model_name: Nombre del modelo
        local_dir: Directorio local del modelo
        device: Dispositivo (cuda/cpu)
        ram_threshold: Umbral de RAM en porcentaje
        vram_threshold: Umbral de VRAM en porcentaje
        check_interval: Intervalo de verificación en segundos

    Returns:
        tuple: (model, num_params, error_message)
    """
    try:
        print(f'   📦 Iniciando carga del modelo...')

        # Verificar memoria antes de empezar
        ram_initial = get_ram_usage()
        vram_initial = get_vram_usage()
        print(f'   📊 Pre-carga -> RAM: {ram_initial:.1f}% | VRAM: {vram_initial:.1f}%')

        if ram_initial > ram_threshold:
            return None, None, f"RAM_TOO_HIGH_BEFORE_LOAD", ram_initial, vram_initial

        if vram_initial > vram_threshold:
            return None, None, f"VRAM_TOO_HIGH_BEFORE_LOAD", ram_initial, vram_initial

        # Cargar el modelo (SIN subprocess, para evitar problemas de serialización)
        start_time = time.time()
        model = SentenceTransformer(local_dir, device=device, trust_remote_code=True, model_kwargs={"torch_dtype": torch.float16, "low_cpu_mem_usage": True})
        load_time = time.time() - start_time

        # Verificar memoria después de cargar
        ram_after = get_ram_usage()
        vram_after = get_vram_usage()
        vram_gb = get_vram_gb()

        print(f'   ✓ Modelo cargado en {load_time:.1f}s')
        print(f'   📊 Post-carga -> RAM: {ram_after:.1f}% | VRAM: {vram_after:.1f}% ({vram_gb:.2f} GB)')

        # Verificar si se excedieron los umbrales DESPUÉS de cargar
        if ram_after > ram_threshold:
            print(f'   ⚠️  RAM excedió umbral después de cargar: {ram_after:.1f}% > {ram_threshold}%')
            del model
            clear_memory()
            return None, None, f"RAM_EXCEEDED_AFTER_LOAD", ram_after, vram_after

        if vram_after > vram_threshold:
            print(f'   ⚠️  VRAM excedió umbral después de cargar: {vram_after:.1f}% > {vram_threshold}%')
            del model
            clear_memory()
            return None, None, f"VRAM_EXCEEDED_AFTER_LOAD", ram_after, vram_after

        # Obtener número de parámetros
        num_params = sum(p.numel() for p in model.parameters())

        return model, num_params, None, ram_after, vram_after

    except RuntimeError as e:
        if "out of memory" in str(e).lower() or "cuda" in str(e).lower():
            ram_curr = get_ram_usage()
            vram_curr = get_vram_usage()
            print(f'   ❌ Error de memoria CUDA: {e}')
            print(f'   📊 Al fallar -> RAM: {ram_curr:.1f}% | VRAM: {vram_curr:.1f}%')
            clear_memory()
            return None, None, f"CUDA_OUT_OF_MEMORY", ram_curr, vram_curr
        else:
            raise

    except Exception as e:
        ram_curr = get_ram_usage()
        vram_curr = get_vram_usage()
        print(f'   ❌ Error inesperado: {str(e)[:100]}')
        return None, None, str(e)[:200], ram_curr, vram_curr

In [ ]:
cache_dir = "/content/hf_cache"

print(f'🚀 Iniciando evaluación con control de RAM y VRAM')
print(f'📊 Umbral RAM: {RAM_THRESHOLD}% | Umbral VRAM: {VRAM_THRESHOLD}%')
print(f'💾 RAM inicial: {get_ram_usage():.1f}%')
if torch.cuda.is_available():
    total_vram_gb = torch.cuda.get_device_properties(0).total_memory / 1024**3
    print(f'🎮 CUDA disponible: {torch.cuda.get_device_name(0)}')
    print(f'🎮 VRAM total: {total_vram_gb:.1f} GB')
    print(f'🎮 VRAM inicial: {get_vram_usage():.1f}% ({get_vram_gb():.2f} GB)')
print('=' * 60)

for index, model_name in enumerate(models):
    if model_name in df.model_name.values or model_name in errors or model_name in combined.model_name.values:
        continue

    if index == 0:
        print('Comenzamos desde el principio')
    else:
        print(f'Continuamos con iteracion {index}.')

    # Estado de memoria antes de empezar
    ram_before = get_ram_usage()
    vram_before = get_vram_usage()
    vram_gb_before = get_vram_gb()
    print(f'📊 Estado inicial -> RAM: {ram_before:.1f}% | VRAM: {vram_before:.1f}% ({vram_gb_before:.2f} GB)')

    # Verificación preventiva
    if ram_before > RAM_THRESHOLD or vram_before > VRAM_THRESHOLD:
        print(f'⚠️  Memoria demasiado alta antes de cargar - Limpiando...')
        clear_memory()
        time.sleep(1)  # Dar tiempo a que se libere
        ram_after_clean = get_ram_usage()
        vram_after_clean = get_vram_usage()
        print(f'📊 Después de limpieza -> RAM: {ram_after_clean:.1f}% | VRAM: {vram_after_clean:.1f}%')

        if ram_after_clean > RAM_THRESHOLD:
            print(f'❌ No se pudo liberar suficiente RAM ({ram_after_clean:.1f}% > {RAM_THRESHOLD}%) - Saltando {model_name}')
            errors.append(model_name)
            reported_errors = pd.concat([reported_errors, pd.DataFrame([{
                'model_name': model_name,
                'error': f'RAM_HIGH_BEFORE_LOAD ({ram_after_clean:.1f}%)'
            }])], ignore_index=True)
            continue

        if vram_after_clean > VRAM_THRESHOLD:
            print(f'❌ No se pudo liberar suficiente VRAM ({vram_after_clean:.1f}% > {VRAM_THRESHOLD}%) - Saltando {model_name}')
            errors.append(model_name)
            reported_errors = pd.concat([reported_errors, pd.DataFrame([{
                'model_name': model_name,
                'error': f'VRAM_HIGH_BEFORE_LOAD ({vram_after_clean:.1f}%)'
            }])], ignore_index=True)
            continue

    print(f'⏳ Cargando modelo {model_name}')

    model = None

    try:
        # Obtener información del modelo
        try:
            info = model_info(model_name)
            langs = info.cardData.get("languages") or info.cardData.get("language")
            mode = 'multilingual' if len(langs) > 1 else 'monolingual'
        except:
            mode = 'unknown'

        # Descarga local (esto no consume tanta RAM)
        print(f'📥 Descargando {model_name}...')
        local_dir = snapshot_download(
            repo_id=model_name,
            cache_dir=cache_dir,
            use_auth_token=True,
            resume_download=True,
            force_download=False,
            local_files_only=False
        )

        # Cargar modelo CON monitoreo de RAM y VRAM
        print(f'🔄 Cargando en memoria y monitoreando recursos...')
        result = load_model_with_monitoring(
            model_name,
            local_dir,
            device,
            RAM_THRESHOLD,
            VRAM_THRESHOLD,
            RAM_CHECK_INTERVAL
        )

        model, num_params, error_msg, ram_val, vram_val = result

        if error_msg:
          print('Carga fallida. Intendando descargar modelo directamente en memoria...')
          result = load_model_with_monitoring(
              model_name,
              model_name, # directamente el modelo
              device,
              RAM_THRESHOLD,
              VRAM_THRESHOLD,
              RAM_CHECK_INTERVAL
          )

          model, num_params, error_msg, ram_val, vram_val = result

        if model is None:
          raise MemoryError(f"Carga fallida: {e} (RAM: {ram_val:.1f}%, VRAM: {vram_val:.1f}%)")


        # Evaluación
        print(f'🧪 Evaluando modelo...')
        evaluation_results = spanish_monolingual_evaluation(model, device, source)

        # Guardar resultados
        df = pd.concat([df, pd.DataFrame([{
            'model_name': model_name,
            'num_params': num_params,
            'languages': mode,
            'map_es_es': evaluation_results.get('map', np.nan),
            'mrr': evaluation_results.get('mrr', np.nan),
            'ndcg': evaluation_results.get('ndcg', np.nan),
            'p@5': evaluation_results.get('precision@5', np.nan),
            'p@10': evaluation_results.get('precision@10', np.nan),
            'p@100': evaluation_results.get('precision@100', np.nan)
        }])], ignore_index=True)

        print(f'✅ Modelo {model_name} evaluado exitosamente. MAP: {evaluation_results.get('map', np.nan)}')

    except MemoryError as e:
        error_detail = str(e)
        print(f'❌ Error de memoria con {model_name}: {error_detail}')
        errors.append(model_name)
        reported_errors = pd.concat([reported_errors, pd.DataFrame([{
            'model_name': model_name,
            'error': error_detail
        }])], ignore_index=True)

    except Exception as e:
        error_detail = str(e)[:200]
        print(f'❌ Error al procesar {model_name}: {error_detail}')
        errors.append(model_name)
        reported_errors = pd.concat([reported_errors, pd.DataFrame([{
            'model_name': model_name,
            'error': error_detail
        }])], ignore_index=True)

    finally:
        # SIEMPRE limpiar memoria
        if model is not None:
            del model
        clear_memory()
        time.sleep(0.5)  # Pequeña pausa para asegurar limpieza

        ram_after_clear = get_ram_usage()
        vram_after_clear = get_vram_usage()
        print(f'🧹 Después de limpieza -> RAM: {ram_after_clear:.1f}% | VRAM: {vram_after_clear:.1f}%')
        print('-' * 60)

        # Borrar modelo de la cache
        if index % 3 == 0:
          for item in os.listdir(cache_dir):
            item_path = os.path.join(cache_dir, item)

            # Si es un directorio, se elimina recursivamente
            if os.path.isdir(item_path):
                shutil.rmtree(item_path)
            # Si es un archivo, se elimina directamente
            elif os.path.isfile(item_path):
                os.remove(item_path)

    # Guardar checkpoint
    if index % 1 == 0:
        df.to_csv(output_dir / 'mteb_evaluation_results_checkpoint.csv', index=False)
        reported_errors.to_csv(output_dir / 'mteb_reported_errors_checkpoint.csv', index=False)
        with open(output_dir / "mteb_errors_checkpoint.txt", "w") as archivo:
            for item in errors:
                archivo.write(f"{item}\n")
        print('=' * 60)
        print(f'💾 Checkpoint guardado en iteracion {index}')
        print(f'📊 Modelos evaluados: {len(df)} | Errores: {len(errors)}')
        print('=' * 60)

print('\n🎉 Evaluación completada!')
print(f'✅ Modelos evaluados: {len(df)}')
print(f'❌ Errores: {len(errors)}')
print(f'📋 Detalles de errores guardados en reported_errors')

🚀 Iniciando evaluación con control de RAM y VRAM
📊 Umbral RAM: 90% | Umbral VRAM: 95%
💾 RAM inicial: 44.8%
🎮 CUDA disponible: Tesla T4
🎮 VRAM total: 14.7 GB
🎮 VRAM inicial: 0.0% (0.00 GB)
============================================================
Continuamos con iteracion 87.
📊 Estado inicial -> RAM: 44.8% | VRAM: 0.0% (0.00 GB)
⏳ Cargando modelo Alibaba-NLP/gte-Qwen2-1.5B-instruct
📥 Descargando Alibaba-NLP/gte-Qwen2-1.5B-instruct...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Fetching 20 files:   0%|          | 0/20 [00:00<?, ?it/s]

README.md: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/80.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/297 [00:00<?, ?B/s]

.gitattributes: 0.00B [00:00, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/284 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/901 [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/117 [00:00<?, ?B/s]

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

modeling_qwen.py: 0.00B [00:00, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/2.11G [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.99G [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/370 [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/55.0 [00:00<?, ?B/s]

eval_mteb.py: 0.00B [00:00, ?B/s]

tokenization_qwen.py: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

🔄 Cargando en memoria y monitoreando recursos...
   📦 Iniciando carga del modelo...
   📊 Pre-carga -> RAM: 25.2% | VRAM: 0.0%

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

   ❌ Error inesperado: 'dict' object has no attribute 'model_type'
Carga fallida. Intendando descargar modelo directamente en memoria...
   📦 Iniciando carga del modelo...
   📊 Pre-carga -> RAM: 47.0% | VRAM: 0.0%

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/284 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/55.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/901 [00:00<?, ?B/s]

modeling_qwen.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/Alibaba-NLP/gte-Qwen2-1.5B-instruct:
- modeling_qwen.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.99G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/2.11G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenization_qwen.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/Alibaba-NLP/gte-Qwen2-1.5B-instruct:
- tokenization_qwen.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/80.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/370 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/297 [00:00<?, ?B/s]

past_key_values should not be None in from_legacy_cache()

   ✓ Modelo cargado en 238.3s
   📊 Post-carga -> RAM: 57.7% | VRAM: 31.4% (4.62 GB)
🧪 Evaluando modelo...
Loading Spanish data...
Encoding data: gte-Qwen2-1.5B-instruct on device: cuda
❌ Error al procesar Alibaba-NLP/gte-Qwen2-1.5B-instruct: 'DynamicCache' object has no attribute 'get_usable_length'
🧹 Después de limpieza -> RAM: 57.6% | VRAM: 31.4%
------------------------------------------------------------
============================================================
💾 Checkpoint guardado en iteracion 87
📊 Modelos evaluados: 51 | Errores: 30
============================================================
Continuamos con iteracion 88.
📊 Estado inicial -> RAM: 57.5% | VRAM: 31.4% (4.62 GB)
⏳ Cargando modelo AIDA-UPM/mstsb-paraphrase-multilingual-mpnet-base-v2
📥 Descargando AIDA-UPM/mstsb-paraphrase-multilingual-mpnet-base-v2...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Fetching 12 files:   0%|          | 0/12 [00:00<?, ?it/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/769 [00:00<?, ?B/s]

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

.gitattributes:   0%|          | 0.00/737 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/490 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

🔄 Cargando en memoria y monitoreando recursos...
   📦 Iniciando carga del modelo...
   📊 Pre-carga -> RAM: 57.3% | VRAM: 31.4%
   ❌ Error inesperado: 'dict' object has no attribute 'model_type'
Carga fallida. Intendando descargar modelo directamente en memoria...
   📦 Iniciando carga del modelo...
   📊 Pre-carga -> RAM: 57.6% | VRAM: 31.4%

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/769 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/490 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

   ✓ Modelo cargado en 55.7s
   📊 Post-carga -> RAM: 63.4% | VRAM: 35.1% (5.17 GB)
🧪 Evaluando modelo...
Loading Spanish data...
Encoding data: mstsb-paraphrase-multilingual-mpnet-base-v2 on device: cuda
Calculating similarities and preparing results...
Evaluating Spanish monolingual performance...

/usr/local/lib/python3.12/dist-packages/ranx/metrics/average_precision.py:49: NumbaTypeSafetyWarning: unsafe cast from uint64 to int64. Precision may be lost.
  scores[i] = _average_precision(qrels[i], run[i], k, rel_lvl)

In [ ]:
df = df.sort_values('map_es_es', ascending=False).reset_index(drop=True)
df.to_csv(output_dir / 'mteb_evaluation_results.csv', index=False)

# los modelos que no se han podido ejecutar es porque son cuantizaciones de modelos mayores que si se han ejecutado
with open(output_dir / "mteb_errors.txt", "w") as archivo:
    for item in errors:
        archivo.write(f"{item}\n")

## Spanish models iteration

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
source = 'validation'

with open(project_dir / 'models' / 'results' / 'spanish' / 'es_models_list.txt', 'r') as file:
    models = file.read().splitlines()

df = pd.DataFrame(columns=['model_name', 'num_params', 'languages', 'map_es_es', 'mrr', 'ndcg', 'p@5', 'p@10', 'p@100'])
errors = []

In [ ]:
for index, model_name in enumerate(models):

  if model_name in df.model_name.values or model_name in errors:
    continue

  if index == 0:
    print('Comenzamos desde el principio')
  else:
    print(f'Continuamos con Iteracion {index}.')

  try:
    info = model_info(model_name)
    langs = info.cardData.get("languages") or info.cardData.get("language")
    mode = 'multilingual' if len(langs) > 1 else 'monolingual'
  except:
    mode = 'monolingual'

  try:
    model = SentenceTransformer(model_name, device=device, trust_remote_code=True)
    evaluation_results = spanish_monolingual_evaluation(model, device, source)
  except:
    errors.append(model_name)
    continue

  num_params = sum(p.numel() for p in model.parameters())

  df = pd.concat([df, pd.DataFrame([{
        'model_name': model_name,
        'num_params': num_params,
        'languages': mode,
        'map_es_es': evaluation_results.get('map', np.nan),
        'mrr': evaluation_results.get('mrr', np.nan),
        'ndcg': evaluation_results.get('ndcg', np.nan),
        'p@5': evaluation_results.get('precision@5', np.nan),
        'p@10': evaluation_results.get('precision@10', np.nan),
        'p@100': evaluation_results.get('precision@100', np.nan)
  }])], ignore_index=True)


  if index % 2 == 0:
    df.to_csv(output_dir / 'es_evaluation_results_checkpoint.csv', index=False)
    with open(output_dir / "es_errors_checkpoint.txt", "w") as archivo:
        for item in errors:
            archivo.write(f"{item}\n")

    print('==========================================')
    print(f'Checkpoint en iteracion {index}')
    print('==========================================')

Continuamos con Iteracion 86.

WARNING:sentence_transformers.SentenceTransformer:No sentence-transformers model found with name jaimevera1107/roberta-similarity-es. Creating a new one with mean pooling.

Continuamos con Iteracion 87.

WARNING:sentence_transformers.SentenceTransformer:No sentence-transformers model found with name bertin-project/bertin-roberta-base-spanish. Creating a new one with mean pooling.

config.json:   0%|          | 0.00/674 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Some weights of RobertaModel were not initialized from the model checkpoint at bertin-project/bertin-roberta-base-spanish and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/772 [00:00<?, ?B/s]

Loading Spanish data...
Encoding data: bertin-roberta-base-spanish on device: cuda
Calculating similarities and preparing results...
Evaluating Spanish monolingual performance...
Spanish evaluation completed
Continuamos con Iteracion 88.

modules.json:   0%|          | 0.00/341 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/703 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/439M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/557 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/439M [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/114 [00:00<?, ?B/s]

2_Dense/pytorch_model.bin:   0%|          | 0.00/789k [00:00<?, ?B/s]

Loading Spanish data...
Encoding data: Model_dccuchile_bert-base-spanish-wwm-uncased_100_Epochs on device: cuda
Calculating similarities and preparing results...
Evaluating Spanish monolingual performance...
Spanish evaluation completed
==========================================
Checkpoint en iteracion 88
==========================================

In [ ]:
df = df.sort_values('map_es_es', ascending=False).reset_index(drop=True)
df.to_csv(output_dir / 'es_evaluation_results.csv', index=False)

# los modelos que no se han podido ejecutar es porque son cuantizaciones de modelos mayores que si se han ejecutado
with open(output_dir / "es_errors.txt", "w") as archivo:
    for item in errors:
        archivo.write(f"{item}\n")

In [ ]:
df

,model_name,num_params,languages,map_es_es,mrr,ndcg,p@5,p@10,p@100
0,PlanTL-GOB-ES/Controversy-Prediction,124643328,monolingual,0.163781,0.458191,0.537438,0.393514,0.356757,0.106595
1,PlanTL-GOB-ES/RoBERTalex,125978112,monolingual,0.106082,0.405401,0.480093,0.302703,0.237838,0.071243
2,PlanTL-GOB-ES/bsc-bio-ehr-es,124643328,monolingual,0.121292,0.423240,0.500913,0.343784,0.290811,0.089189
3,PlanTL-GOB-ES/bsc-bio-ehr-es-cantemist,124643328,monolingual,0.146873,0.454792,0.531166,0.395676,0.342162,0.107568
4,PlanTL-GOB-ES/bsc-bio-ehr-es-pharmaconer,124643328,monolingual,0.129205,0.438381,0.514391,0.367568,0.318919,0.096486
...,...,...,...,...,...,...,...,...,...
80,dccuchile/tulio-chilean-spanish-bert,109850880,monolingual,0.199765,0.474575,0.577699,0.445405,0.365405,0.132054
81,hiiamsid/sentence_similarity_spanish_es,109850880,monolingual,0.359950,0.543644,0.696632,0.614054,0.571351,0.209568
82,hackathon-pln-es/paraphrase-spanish-distilroberta,124645632,monolingual,0.306656,0.506510,0.644225,0.517838,0.489730,0.193946
83,jinaai/jina-embeddings-v2-base-es,160850688,multilingual,0.384104,0.560721,0.708983,0.622703,0.588108,0.215676
84,jaimevera1107/all-MiniLM-L6-v2-similarity-es,22713216,monolingual,0.298559,0.537722,0.637897,0.588108,0.551892,0.164432

## Intento de evaluación de errores

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
source = 'validation'

with open(project_dir / 'models' / 'results' / 'mteb' / 'mteb_errors.txt', 'r') as file:
    models = file.read().splitlines()

models = [model for model in models if model != '']

combined = pd.read_csv(project_dir / 'models' / 'results' / 'evaluation_results.csv')

df = pd.DataFrame(columns=['model_name', 'num_params', 'languages', 'map_es_es', 'mrr', 'ndcg', 'p@5', 'p@10', 'p@100'])
reported_errors = pd.DataFrame(columns=['model_name', 'error'])

errors = []

In [ ]:
df = pd.read_csv('/content/mteb_evaluation_results_checkpoint.csv')
reported_errors = pd.read_csv('/content/mteb_reported_errors_checkpoint.csv')

with open('/content/mteb_errors_checkpoint.txt', "r") as archivo:
    errors = [line.strip() for line in archivo.readlines()]

In [ ]:
df

,model_name,num_params,languages,map_es_es,mrr,ndcg,p@5,p@10,p@100
0,jinaai/jina-embeddings-v3,572310396,multilingual,0.445291,0.547297,0.740716,0.656216,0.615135,0.241892
1,intfloat/multilingual-e5-small,117653760,multilingual,0.351316,0.539189,0.688664,0.608649,0.584865,0.197405
2,intfloat/multilingual-e5-large-instruct,559890432,multilingual,0.442597,0.538243,0.739878,0.658378,0.622162,0.242108
3,intfloat/multilingual-e5-large,559890432,multilingual,0.338105,0.543115,0.683437,0.581622,0.548649,0.197514
4,intfloat/multilingual-e5-base,278043648,multilingual,0.346278,0.539189,0.686449,0.590270,0.559459,0.198432

In [ ]:
errors

['nvidia/NV-Embed-v2',
 'nvidia/NV-Embed-v1',
 'minishlab/potion-multilingual-128M',
 'jinaai/jina-embeddings-v4',
 'intfloat/e5-mistral-7b-instruct']

In [ ]:
# Configuración
RAM_THRESHOLD = 90  # Ajusta según tu entorno (80-85 para Colab)
VRAM_THRESHOLD = 95  # Umbral para VRAM (puede ser más alto que RAM)
RAM_CHECK_INTERVAL = 0.3  # Verificar cada 0.5 segundos

def get_ram_usage():
    """Retorna el porcentaje de RAM utilizado"""
    return psutil.virtual_memory().percent

def get_vram_usage():
    """Retorna el porcentaje de VRAM utilizado"""
    if torch.cuda.is_available():
        total_vram = torch.cuda.get_device_properties(0).total_memory
        allocated_vram = torch.cuda.memory_allocated(0)
        return (allocated_vram / total_vram) * 100
    return 0

def get_vram_gb():
    """Retorna VRAM usado en GB"""
    if torch.cuda.is_available():
        return torch.cuda.memory_allocated(0) / 1024**3
    return 0

def clear_memory():
    """Libera memoria de forma agresiva"""
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.synchronize()

def load_model_with_monitoring(model_name, local_dir, device, ram_threshold=85, vram_threshold=90, check_interval=2.0):
    """
    Carga un modelo monitoreando RAM y VRAM periódicamente durante la carga.

    Args:
        model_name: Nombre del modelo
        local_dir: Directorio local del modelo
        device: Dispositivo (cuda/cpu)
        ram_threshold: Umbral de RAM en porcentaje
        vram_threshold: Umbral de VRAM en porcentaje
        check_interval: Intervalo de verificación en segundos

    Returns:
        tuple: (model, num_params, error_message)
    """
    try:
        print(f'   📦 Iniciando carga del modelo...')

        # Verificar memoria antes de empezar
        ram_initial = get_ram_usage()
        vram_initial = get_vram_usage()
        print(f'   📊 Pre-carga -> RAM: {ram_initial:.1f}% | VRAM: {vram_initial:.1f}%')

        if ram_initial > ram_threshold:
            return None, None, f"RAM_TOO_HIGH_BEFORE_LOAD", ram_initial, vram_initial

        if vram_initial > vram_threshold:
            return None, None, f"VRAM_TOO_HIGH_BEFORE_LOAD", ram_initial, vram_initial

        # Cargar el modelo (SIN subprocess, para evitar problemas de serialización)
        start_time = time.time()
        model = SentenceTransformer(local_dir, device=device, trust_remote_code=True, model_kwargs={"torch_dtype": torch.float16, "low_cpu_mem_usage": True})
        load_time = time.time() - start_time

        # Verificar memoria después de cargar
        ram_after = get_ram_usage()
        vram_after = get_vram_usage()
        vram_gb = get_vram_gb()

        print(f'   ✓ Modelo cargado en {load_time:.1f}s')
        print(f'   📊 Post-carga -> RAM: {ram_after:.1f}% | VRAM: {vram_after:.1f}% ({vram_gb:.2f} GB)')

        # Verificar si se excedieron los umbrales DESPUÉS de cargar
        if ram_after > ram_threshold:
            print(f'   ⚠️  RAM excedió umbral después de cargar: {ram_after:.1f}% > {ram_threshold}%')
            del model
            clear_memory()
            return None, None, f"RAM_EXCEEDED_AFTER_LOAD", ram_after, vram_after

        if vram_after > vram_threshold:
            print(f'   ⚠️  VRAM excedió umbral después de cargar: {vram_after:.1f}% > {vram_threshold}%')
            del model
            clear_memory()
            return None, None, f"VRAM_EXCEEDED_AFTER_LOAD", ram_after, vram_after

        # Obtener número de parámetros
        num_params = sum(p.numel() for p in model.parameters())

        return model, num_params, None, ram_after, vram_after

    except RuntimeError as e:
        if "out of memory" in str(e).lower() or "cuda" in str(e).lower():
            ram_curr = get_ram_usage()
            vram_curr = get_vram_usage()
            print(f'   ❌ Error de memoria CUDA: {e}')
            print(f'   📊 Al fallar -> RAM: {ram_curr:.1f}% | VRAM: {vram_curr:.1f}%')
            clear_memory()
            return None, None, f"CUDA_OUT_OF_MEMORY", ram_curr, vram_curr
        else:
            raise

    except Exception as e:
        ram_curr = get_ram_usage()
        vram_curr = get_vram_usage()
        print(f'   ❌ Error inesperado: {str(e)[:100]}')
        return None, None, str(e)[:200], ram_curr, vram_curr

In [ ]:
cache_dir = "/content/hf_cache"

print(f'🚀 Iniciando evaluación con control de RAM y VRAM')
print(f'📊 Umbral RAM: {RAM_THRESHOLD}% | Umbral VRAM: {VRAM_THRESHOLD}%')
print(f'💾 RAM inicial: {get_ram_usage():.1f}%')
if torch.cuda.is_available():
    total_vram_gb = torch.cuda.get_device_properties(0).total_memory / 1024**3
    print(f'🎮 CUDA disponible: {torch.cuda.get_device_name(0)}')
    print(f'🎮 VRAM total: {total_vram_gb:.1f} GB')
    print(f'🎮 VRAM inicial: {get_vram_usage():.1f}% ({get_vram_gb():.2f} GB)')
print('=' * 60)

for index, model_name in enumerate(models):
    if model_name in df.model_name.values or model_name in errors or model_name in combined.model_name.values:
        continue

    if index == 0:
        print('Comenzamos desde el principio')
    else:
        print(f'Continuamos con iteracion {index}.')

    # Estado de memoria antes de empezar
    ram_before = get_ram_usage()
    vram_before = get_vram_usage()
    vram_gb_before = get_vram_gb()
    print(f'📊 Estado inicial -> RAM: {ram_before:.1f}% | VRAM: {vram_before:.1f}% ({vram_gb_before:.2f} GB)')

    # Verificación preventiva
    if ram_before > RAM_THRESHOLD or vram_before > VRAM_THRESHOLD:
        print(f'⚠️  Memoria demasiado alta antes de cargar - Limpiando...')
        clear_memory()
        time.sleep(1)  # Dar tiempo a que se libere
        ram_after_clean = get_ram_usage()
        vram_after_clean = get_vram_usage()
        print(f'📊 Después de limpieza -> RAM: {ram_after_clean:.1f}% | VRAM: {vram_after_clean:.1f}%')

        if ram_after_clean > RAM_THRESHOLD:
            print(f'❌ No se pudo liberar suficiente RAM ({ram_after_clean:.1f}% > {RAM_THRESHOLD}%) - Saltando {model_name}')
            errors.append(model_name)
            reported_errors = pd.concat([reported_errors, pd.DataFrame([{
                'model_name': model_name,
                'error': f'RAM_HIGH_BEFORE_LOAD ({ram_after_clean:.1f}%)'
            }])], ignore_index=True)
            continue

        if vram_after_clean > VRAM_THRESHOLD:
            print(f'❌ No se pudo liberar suficiente VRAM ({vram_after_clean:.1f}% > {VRAM_THRESHOLD}%) - Saltando {model_name}')
            errors.append(model_name)
            reported_errors = pd.concat([reported_errors, pd.DataFrame([{
                'model_name': model_name,
                'error': f'VRAM_HIGH_BEFORE_LOAD ({vram_after_clean:.1f}%)'
            }])], ignore_index=True)
            continue

    print(f'⏳ Cargando modelo {model_name}')

    model = None

    try:
        # Obtener información del modelo
        try:
            info = model_info(model_name)
            langs = info.cardData.get("languages") or info.cardData.get("language")
            mode = 'multilingual' if len(langs) > 1 else 'monolingual'
        except:
            mode = 'unknown'

        # Descarga local (esto no consume tanta RAM)
        print(f'📥 Descargando {model_name}...')
        local_dir = snapshot_download(
            repo_id=model_name,
            cache_dir=cache_dir,
            use_auth_token=True,
            resume_download=True,
            force_download=False,
            local_files_only=False
        )

        # Cargar modelo CON monitoreo de RAM y VRAM
        print(f'🔄 Cargando en memoria y monitoreando recursos...')
        result = load_model_with_monitoring(
            model_name,
            local_dir,
            device,
            RAM_THRESHOLD,
            VRAM_THRESHOLD,
            RAM_CHECK_INTERVAL
        )

        model, num_params, error_msg, ram_val, vram_val = result

        if error_msg:
          print('Carga fallida. Intendando descargar modelo directamente en memoria...')
          result = load_model_with_monitoring(
              model_name,
              model_name, # directamente el modelo
              device,
              RAM_THRESHOLD,
              VRAM_THRESHOLD,
              RAM_CHECK_INTERVAL
          )

          model, num_params, error_msg, ram_val, vram_val = result

        if model is None:
          raise MemoryError(f"Carga fallida: {e} (RAM: {ram_val:.1f}%, VRAM: {vram_val:.1f}%)")


        # Evaluación
        print(f'🧪 Evaluando modelo...')
        evaluation_results = spanish_monolingual_evaluation(model, device, source)

        # Guardar resultados
        df = pd.concat([df, pd.DataFrame([{
            'model_name': model_name,
            'num_params': num_params,
            'languages': mode,
            'map_es_es': evaluation_results.get('map', np.nan),
            'mrr': evaluation_results.get('mrr', np.nan),
            'ndcg': evaluation_results.get('ndcg', np.nan),
            'p@5': evaluation_results.get('precision@5', np.nan),
            'p@10': evaluation_results.get('precision@10', np.nan),
            'p@100': evaluation_results.get('precision@100', np.nan)
        }])], ignore_index=True)

        print(f'✅ Modelo {model_name} evaluado exitosamente. MAP: {evaluation_results.get('map', np.nan)}')

    except MemoryError as e:
        error_detail = str(e)
        print(f'❌ Error de memoria con {model_name}: {error_detail}')
        errors.append(model_name)
        reported_errors = pd.concat([reported_errors, pd.DataFrame([{
            'model_name': model_name,
            'error': error_detail
        }])], ignore_index=True)

    except Exception as e:
        error_detail = str(e)[:200]
        print(f'❌ Error al procesar {model_name}: {error_detail}')
        errors.append(model_name)
        reported_errors = pd.concat([reported_errors, pd.DataFrame([{
            'model_name': model_name,
            'error': error_detail
        }])], ignore_index=True)

    finally:
        # SIEMPRE limpiar memoria
        if model is not None:
            del model
        clear_memory()
        time.sleep(0.5)  # Pequeña pausa para asegurar limpieza

        ram_after_clear = get_ram_usage()
        vram_after_clear = get_vram_usage()
        print(f'🧹 Después de limpieza -> RAM: {ram_after_clear:.1f}% | VRAM: {vram_after_clear:.1f}%')
        print('-' * 60)

        # Borrar modelo de la cache
        if index % 3 == 0:
          for item in os.listdir(cache_dir):
            item_path = os.path.join(cache_dir, item)

            # Si es un directorio, se elimina recursivamente
            if os.path.isdir(item_path):
                shutil.rmtree(item_path)
            # Si es un archivo, se elimina directamente
            elif os.path.isfile(item_path):
                os.remove(item_path)

    # Guardar checkpoint
    if index % 1 == 0:
        df.to_csv(output_dir / 'mteb_evaluation_results_checkpoint.csv', index=False)
        reported_errors.to_csv(output_dir / 'mteb_reported_errors_checkpoint.csv', index=False)
        with open(output_dir / "mteb_errors_checkpoint.txt", "w") as archivo:
            for item in errors:
                archivo.write(f"{item}\n")
        print('=' * 60)
        print(f'💾 Checkpoint guardado en iteracion {index}')
        print(f'📊 Modelos evaluados: {len(df)} | Errores: {len(errors)}')
        print('=' * 60)

print('\n🎉 Evaluación completada!')
print(f'✅ Modelos evaluados: {len(df)}')
print(f'❌ Errores: {len(errors)}')
print(f'📋 Detalles de errores guardados en reported_errors')

🚀 Iniciando evaluación con control de RAM y VRAM
📊 Umbral RAM: 90% | Umbral VRAM: 95%
💾 RAM inicial: 5.1%
============================================================
Comenzamos desde el principio
📊 Estado inicial -> RAM: 5.1% | VRAM: 0.0% (0.00 GB)
⏳ Cargando modelo sentence-transformers/static-similarity-mrl-multilingual-v1
📥 Descargando sentence-transformers/static-similarity-mrl-multilingual-v1...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Fetching 18 files:   0%|          | 0/18 [00:00<?, ?it/s]

README.md: 0.00B [00:00, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/214 [00:00<?, ?B/s]

similarity_mteb_eval.png:   0%|          | 0.00/88.0k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

.gitattributes: 0.00B [00:00, ?B/s]

similarity_matryoshka.png:   0%|          | 0.00/90.1k [00:00<?, ?B/s]

similarity_speed.png:   0%|          | 0.00/36.2k [00:00<?, ?B/s]

modules.json:   0%|          | 0.00/141 [00:00<?, ?B/s]

0_StaticEmbedding/model.safetensors:   0%|          | 0.00/434M [00:00<?, ?B/s]

onnx/model.onnx:   0%|          | 0.00/434M [00:00<?, ?B/s]

onnx/model_bnb4.onnx:   0%|          | 0.00/434M [00:00<?, ?B/s]

onnx/model_int8.onnx:   0%|          | 0.00/108M [00:00<?, ?B/s]

onnx/model_fp16.onnx:   0%|          | 0.00/217M [00:00<?, ?B/s]

onnx/model_q4f16.onnx:   0%|          | 0.00/217M [00:00<?, ?B/s]

train.py: 0.00B [00:00, ?B/s]

🔄 Cargando en memoria y monitoreando recursos...
   📦 Iniciando carga del modelo...
   📊 Pre-carga -> RAM: 5.8% | VRAM: 0.0%
   ✓ Modelo cargado en 0.1s
   📊 Post-carga -> RAM: 5.9% | VRAM: 0.0% (0.00 GB)
🧪 Evaluando modelo...
Loading Spanish data...
❌ Error al procesar sentence-transformers/static-similarity-mrl-multilingual-v1: 'StaticEmbedding' object has no attribute 'auto_model'
🧹 Después de limpieza -> RAM: 5.9% | VRAM: 0.0%
------------------------------------------------------------
============================================================
💾 Checkpoint guardado en iteracion 0
📊 Modelos evaluados: 5 | Errores: 6
============================================================
Continuamos con iteracion 1.
📊 Estado inicial -> RAM: 5.9% | VRAM: 0.0% (0.00 GB)
⏳ Cargando modelo parasail-ai/GritLM-7B-vllm
📥 Descargando parasail-ai/GritLM-7B-vllm...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Fetching 19 files:   0%|          | 0/19 [00:00<?, ?it/s]

config.json:   0%|          | 0.00/934 [00:00<?, ?B/s]

.gitattributes: 0.00B [00:00, ?B/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

dataset_num_samples.json:   0%|          | 0.00/932 [00:00<?, ?B/s]

model-00001-of-00003.safetensors:   0%|          | 0.00/4.94G [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

model-00003-of-00003.safetensors:   0%|          | 0.00/4.54G [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

modeling_gritlm7b.py: 0.00B [00:00, ?B/s]

pytorch_model-00002-of-00003.bin:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

pytorch_model-00001-of-00003.bin:   0%|          | 0.00/4.94G [00:00<?, ?B/s]

pytorch_model.bin.index.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/436 [00:00<?, ?B/s]

pytorch_model-00003-of-00003.bin:   0%|          | 0.00/4.54G [00:00<?, ?B/s]

model-00002-of-00003.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/493k [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

training_args.bin:   0%|          | 0.00/4.98k [00:00<?, ?B/s]

WARNING:sentence_transformers.SentenceTransformer:No sentence-transformers model found with name /content/hf_cache/models--parasail-ai--GritLM-7B-vllm/snapshots/d6ec7afefec5032020b47db967a86e556312c957. Creating a new one with mean pooling.

🔄 Cargando en memoria y monitoreando recursos...
   📦 Iniciando carga del modelo...
   📊 Pre-carga -> RAM: 8.6% | VRAM: 0.0%

`torch_dtype` is deprecated! Use `dtype` instead!

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

past_key_values should not be None in from_legacy_cache()

   ✓ Modelo cargado en 732.0s
   📊 Post-carga -> RAM: 37.8% | VRAM: 0.0% (0.00 GB)
🧪 Evaluando modelo...
Loading Spanish data...
Encoding data: d6ec7afefec5032020b47db967a86e556312c957 on device: cpu
❌ Error al procesar parasail-ai/GritLM-7B-vllm: 'DynamicCache' object has no attribute 'get_usable_length'
🧹 Después de limpieza -> RAM: 37.8% | VRAM: 0.0%
------------------------------------------------------------
============================================================
💾 Checkpoint guardado en iteracion 1
📊 Modelos evaluados: 5 | Errores: 7
============================================================
Continuamos con iteracion 4.
📊 Estado inicial -> RAM: 37.8% | VRAM: 0.0% (0.00 GB)
⏳ Cargando modelo nan
📥 Descargando nan...
❌ Error al procesar nan: 404 Client Error. (Request ID: Root=1-6939a60f-0750637d0acb3c8606a7bfe2;a5e42aaa-6c68-40da-92bd-9545e4f6ef44)

Repository Not Found for url: https://huggingface.co/api/models/nan/revision/main.
Please
🧹 Después de limpieza -> RAM: 37.8% | VRAM: 0.0%
------------------------------------------------------------
============================================================
💾 Checkpoint guardado en iteracion 4
📊 Modelos evaluados: 5 | Errores: 8
============================================================
Continuamos con iteracion 13.
📊 Estado inicial -> RAM: 37.8% | VRAM: 0.0% (0.00 GB)
⏳ Cargando modelo intfloat/e5-large-v2
📥 Descargando intfloat/e5-large-v2...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Fetching 20 files:   0%|          | 0/20 [00:00<?, ?it/s]

onnx/model.onnx:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

modules.json:   0%|          | 0.00/387 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/201 [00:00<?, ?B/s]

.gitattributes: 0.00B [00:00, ?B/s]

handler.py: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/616 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

onnx/model_O4.onnx:   0%|          | 0.00/668M [00:00<?, ?B/s]

openvino/openvino_model.bin:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

onnx/model_qint8_avx512_vnni.onnx:   0%|          | 0.00/337M [00:00<?, ?B/s]

openvino/openvino_model_qint8_quantized.(…):   0%|          | 0.00/337M [00:00<?, ?B/s]

openvino_model.xml: 0.00B [00:00, ?B/s]

openvino_model_qint8_quantized.xml: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer_config.json:   0%|          | 0.00/314 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

🔄 Cargando en memoria y monitoreando recursos...
   📦 Iniciando carga del modelo...
   📊 Pre-carga -> RAM: 37.9% | VRAM: 0.0%
   ✓ Modelo cargado en 1.1s
   📊 Post-carga -> RAM: 38.8% | VRAM: 0.0% (0.00 GB)
🧪 Evaluando modelo...
Loading Spanish data...
Encoding data: f169b11e22de13617baa190a028a32f3493550b6 on device: cpu
Calculating similarities and preparing results...
Evaluating Spanish monolingual performance...

/usr/local/lib/python3.12/dist-packages/ranx/metrics/average_precision.py:49: NumbaTypeSafetyWarning: unsafe cast from uint64 to int64. Precision may be lost.
  scores[i] = _average_precision(qrels[i], run[i], k, rel_lvl)

Spanish evaluation completed
✅ Modelo intfloat/e5-large-v2 evaluado exitosamente. MAP: 0.29519154190598773
🧹 Después de limpieza -> RAM: 11.6% | VRAM: 0.0%
------------------------------------------------------------
============================================================
💾 Checkpoint guardado en iteracion 13
📊 Modelos evaluados: 6 | Errores: 8
============================================================
Continuamos con iteracion 14.
📊 Estado inicial -> RAM: 11.6% | VRAM: 0.0% (0.00 GB)
⏳ Cargando modelo intfloat/e5-base-v2
📥 Descargando intfloat/e5-base-v2...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Fetching 24 files:   0%|          | 0/24 [00:00<?, ?it/s]

onnx/model.onnx:   0%|          | 0.00/436M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/650 [00:00<?, ?B/s]

modules.json:   0%|          | 0.00/387 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/200 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/632 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

.gitattributes: 0.00B [00:00, ?B/s]

onnx/model_qint8_avx512_vnni.onnx:   0%|          | 0.00/110M [00:00<?, ?B/s]

onnx/model_O4.onnx:   0%|          | 0.00/218M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer_config.json:   0%|          | 0.00/314 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

openvino/openvino_model.bin:   0%|          | 0.00/436M [00:00<?, ?B/s]

openvino/openvino_model_qint8_quantized.(…):   0%|          | 0.00/110M [00:00<?, ?B/s]

openvino_model.xml: 0.00B [00:00, ?B/s]

openvino_model_qint8_quantized.xml: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

🔄 Cargando en memoria y monitoreando recursos...
   📦 Iniciando carga del modelo...
   📊 Pre-carga -> RAM: 12.0% | VRAM: 0.0%
   ✓ Modelo cargado en 0.2s
   📊 Post-carga -> RAM: 12.0% | VRAM: 0.0% (0.00 GB)
🧪 Evaluando modelo...
Loading Spanish data...
Encoding data: f52bf8ec8c7124536f0efb74aca902b2995e5bcd on device: cpu
Calculating similarities and preparing results...
Evaluating Spanish monolingual performance...
Spanish evaluation completed
✅ Modelo intfloat/e5-base-v2 evaluado exitosamente. MAP: 0.2991936100131442
🧹 Después de limpieza -> RAM: 11.8% | VRAM: 0.0%
------------------------------------------------------------
============================================================
💾 Checkpoint guardado en iteracion 14
📊 Modelos evaluados: 7 | Errores: 8
============================================================
Continuamos con iteracion 15.
📊 Estado inicial -> RAM: 11.8% | VRAM: 0.0% (0.00 GB)
⏳ Cargando modelo infly/inf-retriever-v1
📥 Descargando infly/inf-retriever-v1...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Fetching 19 files:   0%|          | 0/19 [00:00<?, ?it/s]

.gitattributes: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/873 [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/80.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/298 [00:00<?, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/284 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

model-00001-of-00003.safetensors:   0%|          | 0.00/4.87G [00:00<?, ?B/s]

modeling_qwen.py: 0.00B [00:00, ?B/s]

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/370 [00:00<?, ?B/s]

model-00002-of-00003.safetensors:   0%|          | 0.00/4.93G [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/56.0 [00:00<?, ?B/s]

tokenization_qwen.py: 0.00B [00:00, ?B/s]

model-00003-of-00003.safetensors:   0%|          | 0.00/4.33G [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

🔄 Cargando en memoria y monitoreando recursos...
   📦 Iniciando carga del modelo...
   📊 Pre-carga -> RAM: 12.5% | VRAM: 0.0%

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

   ✓ Modelo cargado en 10.2s
   📊 Post-carga -> RAM: 43.1% | VRAM: 0.0% (0.00 GB)
🧪 Evaluando modelo...
Loading Spanish data...
Encoding data: 8f1be76584d7beaa6ed08419872ef7454de8e88f on device: cpu

In [ ]:
df = df.sort_values('map_es_es', ascending=False).reset_index(drop=True)
df.to_csv(output_dir / 'results_from_errors.csv', index=False)

reported_errors.to_csv(output_dir / 'reported_errors.csv', index=False)

with open(output_dir / "mteb_errors.txt", "w") as archivo:
    for item in errors:
        archivo.write(f"{item}\n")